theme: jekyll-theme-minimal
title: Alex Chen
description: Python | Machine Learning | Computer Science @ McMaster
logo: /images/profile_image.png
show_downloads: true
google_analytics: [UA-175791564-1]
